[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
clear_env = no
decorate_workers_output = no

; Fichier de configuration de PHP-FPM, qui fait tourner WordPress.
; User et group sont définis à www-data, qui est l'utilisateur par défaut pour les processus web.
; Le processus écoute sur le port 9000.
; pm = dynamic signifie que le nombre de processus enfants est ajusté dynamiquement en fonction de la charge.
; children max est limité à 5 pour éviter de surcharger le serveur.
; start_servers définit le nombre de processus enfants à démarrer au lancement.
; min_spare_servers et max_spare_servers définissent le nombre minimum et maximum de processus en attente.